defaults:
  - model                         : vae
  - override hydra/sweeper        : optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: sphere
    storage: null
    n_trials: 20
    n_jobs: 1
    # search_space: ${search_spaces}
    # params:
    #   kld_weight: choice(0.0001, 0.001, 0.01)

datamodule:
  name       : "mnist"
  data_dir   : "./data/"
  # batch_size : 256
  # shuffle    : False
  # num_workers: 0
  # pin_memory : False

logger:
  save_dir: "logs/"
  name    : "VAE"

experiment:
  manual_seed: 1265

trainer:
  gpus                : [0]
  limit_train_batches : 100
  max_epochs          : 2

checkpoint:
  every_n_epochs          : 1
  monitor                 : "Reconstruction_Loss"
  save_last               : False
  save_on_train_epoch_end : True


