defaults:
  - model    : c-dsvae
  # - model    : dsvae_valve
  - raytune  : async_with_optuna
  - notify   : slack

reload:
  path:

datamodule:
  name       : "sprite_aug"
  # name       : "action_norm_valve"
  data_dir   : "./data/"
  batch_size : 128

logger:
  save_dir: "logs/"
  name    : "C-DSVAE"

experiment:
  manual_seed: 1265

trainer:
  gpus                : [0]
  limit_train_batches : 100
  max_epochs          : 500

optimizer:
  lr: 0.001
  betas: [0.9, 0.999]

checkpoint:
  every_n_epochs          : 50
  save_top_k              : -1
  save_last               : True
  # save_on_train_epoch_end : True
  monitor                 : "loss"