defaults:
  - model    : dsvae_valve
  - raytune  : async_with_optuna
  - notify   : slack

reload:
  path:

datamodule:
  name       : "action_norm_valve"
  data_dir   : "./data/"

logger:
  save_dir: "logs/"
  name    : "DSVAE"

experiment:
  manual_seed: 1265

trainer:
  gpus                : [0]
  limit_train_batches : 100
  max_epochs          : 500

checkpoint:
  every_n_epochs          : 50
  save_top_k              : -1
  save_last               : True
  # save_on_train_epoch_end : True
  monitor                 : "loss"